### PR TITLE
Build: Adding necessary packages

### LINKED ISSUE #6: Download necessary packages for the project

### PR DESCRIPTION
**Pull request by Rofy87**
**These are the packages :**

-router
-redux
-react-bootstrap
-react-firebase
-react-i18next  -i18next-browser-languagedetector - i18next-http-backend (for internationalization and automatic detect of the user's language)
-react-icons
-formik
-react-test-renderer (for jest snapshot test)
-node-sass (new one to write SASS)

### CODE REVIEW

**Comment by mustafaguldag** [comment]
I think we have all the packages here that we need. Thank you Rahaf.

**Review by mustafaguldag — APPROVED** [review]
I think we have all the packages here that we need. Thank you Rahaf.

**Comment by halitbatur** [comment]
@Rofy87 We will be using yarn instead of npm could u make sure that the packages are downloaded using yarn ?

**Comment by Rofy87** [comment]
@halitbatur what exactly should i do halit. ? should i make new pull request using yarn so only the yarn.lock would be change so we wont have package.lock or what exactly?

**Comment by halitbatur** [comment]
@Rofy87 Yes I think creating another PR using yarn would work

**Pull request closed without merging**
